CREATE TABLE writings
(
  id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  content TEXT NOT NULL,
  status INT(11) DEFAULT '1' NOT NULL,
  uid INT(11) NOT NULL COMMENT '用户id',
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  type INT(11) NOT NULL
);